### ISSUE TITLE
Configure Prettier and ESLint

### ISSUE THREAD

**Issue by j-wiren** [c-wiren/snackstoppen2#1]

**Comment by j-wiren** [comment]
I added configs for prettier and eslint to the linked branch. You can take a look @c-wiren and run `npm run lint` to check the errors with the current setup. If it's too strict or if you want to add any rules, just do so 😊

**Comment by c-wiren** [comment]
It would be cool to have a GitHub action run the linting on each PR and only allow merging if it succeeds
